apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: {{ .Values.project_name }}
spec:
  entrypoint: dag
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - "ReadWriteMany"
      storageClassName: {{ .Values.storage_class }}
      resources:
        requests:
          storage: 10Gi
  templates:
  - name: kedro
    retryStrategy:
      limit: 1
    inputs:
      parameters:
      - name: kedro_node
    container:
      image: {{ .Values.image }}
      command: [/bin/sh]
      args: ["-c", {{printf "kedro run -n {{%s}} --env=argo" "inputs.parameters.kedro_node" | quote}}]
      volumeMounts:
        - name: data
          mountPath: /home/kedro/data
  - name: dag
    dag:
      tasks:
      {{- range .Values.tasks }}
      - name: {{ .name }}
        template: kedro
        dependencies: 
        {{- range .dep }}
          - {{ . }}
        {{- end }}
        arguments:
          parameters:
          - name: kedro_node
            value: {{ .node }}
      {{- end }}
